In [2]:
import pandas as pd    
from pandas.api.types import is_string_dtype
from pandas.api.types import is_numeric_dtype

In [3]:
gdp_countries = pd.read_excel("Old/original_P_Data_Extract_From_World_Development_Indicators.xlsx")
countries_of_interest = pd.read_csv("countries_of_interest_data.csv", low_memory=False)
gdp_columns = ['Country Code', '2014 [YR2014]', '2015 [YR2015]', '2016 [YR2016]','2017 [YR2017]','2018 [YR2018]','2019 [YR2019]'] 

gdp_c= gdp_countries['Country Code'].unique().tolist()

Creating a seperate Dataframe for Origin GDP from the GDP Data set in the "Old" Folder

In [4]:
countries_origin = countries_of_interest['origin_alpha_3'].unique().tolist()

missing_origin = [i for i in countries_origin if i not in gdp_c]


origin_gpd = gdp_countries[gdp_countries['Country Code'].isin(countries_origin)]

origin_gpd = origin_gpd[gdp_columns]
origin_gpd_frame = pd.DataFrame(origin_gpd)
origin_gpd_frame.reset_index(drop=True, inplace=True)
origin_gpd_frame = origin_gpd_frame.rename(columns={'Country Code':'origin_alpha_3', '2014 [YR2014]':'origin_gdp_2014', '2015 [YR2015]':'origin_gdp_2015', '2016 [YR2016]':'origin_gdp_2016','2017 [YR2017]':'origin_gdp_2017','2018 [YR2018]':'origin_gdp_2018','2019 [YR2019]':'origin_gdp_2019'})
origin_gpd_frame

,origin_alpha_3,origin_gdp_2014,origin_gdp_2015,origin_gdp_2016,origin_gdp_2017,origin_gdp_2018,origin_gdp_2019
0,AFG,20497128600.336327,19134221744.529369,18116572399.129799,18753456506.570824,18053222734.888084,18799444414.599796
1,AGO,135966802156.542297,90496420626.17897,52761617225.925285,73690155046.555038,79450688232.001144,70897962712.621307
2,BIH,18558733564.4692,16404348871.443703,17116926327.624695,18326373366.110527,20484053868.92458,20482608755.378956
3,BDI,2705783329.804834,3104003546.264973,2644487776.500767,2723586962.840337,2667182199.51333,2576518879.823531
4,TCD,13940767218.584887,10950392256.954294,10097778098.170738,10000394381.017702,11239167898.339537,11314951091.728327
5,COL,381240864422.406616,293492370228.843994,282720100286.228455,311866875135.577637,334198218100.718567,323031701210.765259
6,COD,35909040925.937469,37917706497.179283,37134801555.332191,38019264794.82634,47568210009.817162,51775829877.208817
7,CIV,48843005625.579597,45815005170.814972,48407761031.922615,52512344033.768761,58522477744.544388,59898479821.232292
8,ERI,..,..,..,..,..,..
9,ETH,55612228233.51786,64589328550.595299,74296745207.872086,81770886825.604767,84269196625.878403,95912607722.303207
10,IRQ,228415656174.957123,166774104959.101685,166602488747.884949,187217660050.67569,227367469034.030853,233636097800.33844
11,XK,7074394734.884315,6295848422.715734,6682677289.989938,7180764703.357184,7878759714.823217,7899737577.472862
12,LBN,48095213746.600334,49929337836.815918,51147308774.129356,53027680685.903816,54901519155.555557,51605959131.274132
13,LBR,3225652000,3227075700,3398419600,3390703400,3422754800,3319596500
14,LBY,57372352561.987411,48717506273.439873,49912085228.288727,67157451661.404999,76686048497.480133,69254143966.818237
15,MOZ,17978246586.066242,16208985769.614956,12069051237.171114,13264640645.776791,15017358750.611343,15512759174.573046
16,MMR,65446196919.68132,59687411768.822441,63216143490.142319,66055090634.451828,67855845007.316803,75072038085.854172
17,SLE,5015180725.341599,4252029353.821908,3862721266.021616,3719443418.261553,4085114387.556054,4076578698.791073
18,SOM,6537360532.642054,6984947145.093685,7390796616.530291,8252394373.298754,8278212314.405913,9420431258.246672
19,SSD,13962212847.457626,11997800760.224182,..,..,..,..
20,LKA,82528535713.92601,85140955388.850922,88012282205.835709,94376237797.23674,94493871200.78688,89014978344.140396
21,SDN,76818769321.303772,84984666745.108032,102943509633.572968,129718581297.431229,32333780383.292381,32338079165.289257
22,SYR,21502061466.067028,16468399173.000561,12598742889.27318,16369724424.258505,21496337948.91753,22600896342.939903
23,UKR,133503871861.723297,91030967789.071747,93355869403.922318,112090505081.738617,130891088293.549988,153883047509.576965
24,YEM,43228585321.387459,42444489460.80162,31317824906.43943,26842228804.562843,21606160777.171909,..

Creating a seperate Dataframe for Destination GDP from the GDP Data set in the "Old" Folder

In [5]:
countries_destination = countries_of_interest['destination_alpha_3'].unique().tolist()


missing_destination = [i for i in countries_origin if i not in gdp_c]
destination_gpd = gdp_countries[gdp_countries['Country Code'].isin(countries_destination)] 
destination_gpd = destination_gpd[gdp_columns]
destination_gpd_frame = pd.DataFrame(destination_gpd)
destination_gpd_frame.reset_index(drop=True, inplace=True)
destination_gpd_frame = destination_gpd_frame.rename(columns={'Country Code':'destination_alpha_3', '2014 [YR2014]':'destination_gdp_2014', '2015 [YR2015]':'destination_gdp_2015', '2016 [YR2016]':'destination_gdp_2016','2017 [YR2017]':'destination_gdp_2017','2018 [YR2018]':'destination_gdp_2018','2019 [YR2019]':'destination_gdp_2019'})
destination_gpd_frame

,destination_alpha_3,destination_gdp_2014,destination_gdp_2015,destination_gdp_2016,destination_gdp_2017,destination_gdp_2018,destination_gdp_2019
0,AFG,20497128600.336327,19134221744.529369,18116572399.129799,18753456506.570824,18053222734.888084,18799444414.599796
1,ALB,13228147516.116798,11386853113.0189,11861199830.83956,13019726211.736889,15156424015.197748,15401826127.253857
2,DZA,213809979836.313995,165979224866.131348,160034212126.018005,170096988531.905914,174910684781.570557,171760275466.609863
3,AND,3271686452.476858,2789882569.100495,2896611878.625801,3000160414.637949,3218418631.675786,3155150255.911947
4,AGO,135966802156.542297,90496420626.17897,52761617225.925285,73690155046.555038,79450688232.001144,70897962712.621307
...,...,...,...,...,...,...,...
188,VIR,3565000000,3663000000,3798000000,3794000000,3923000000,4121000000
189,PSE,13989700000,13972400000,15405400000,16128000000,16276600000,17133500000
190,YEM,43228585321.387459,42444489460.80162,31317824906.43943,26842228804.562843,21606160777.171909,..
191,ZMB,27141023558.082859,21251216798.776245,20958412538.309345,25873601260.835304,26311507273.673538,23308667781.225754
192,ZWE,19495519600,19963120600,20548678100,17584890936.652306,34156069918.06094,21832234921.176224

Following codes for the destination countries are missing in the new data
['ALA', 'GGY', 'SHN', 'AIA', 'GUF', 'GLP', 'QS', 'BES', 'XC', 'MTQ', 'QW', 'QV', 'QU']

Dropping the previous GDP data from the countries_of_interest dataset

In [6]:
countries_of_interest.drop([col for col in countries_of_interest.columns if 'gdp' in col],axis=1, inplace=True)

Merging Origin GDP into countries_of_interest Data

In [7]:
GDP_merged = countries_of_interest.merge(origin_gpd_frame,on = 'origin_alpha_3', how = 'left')
GDP_merged

,Unnamed: 0,from_to,origin_country,ESTAT_2014_T_T_cit,ESTAT_2014_T_T_res,ESTAT_2014_T_<15_cit,ESTAT_2014_T_<15_res,ESTAT_2014_T_15-64_cit,ESTAT_2014_T_15-64_res,ESTAT_2014_T_>64_cit,...,UN_migr_stocks_2015_F_T,UN_migr_stocks_2020_F_T,origin_alpha_3,destination_alpha_3,origin_gdp_2014,origin_gdp_2015,origin_gdp_2016,origin_gdp_2017,origin_gdp_2018,origin_gdp_2019
0,147,AF-AR,AF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.0,7.0,AFG,ARG,20497128600.336327,19134221744.529369,18116572399.129799,18753456506.570824,18053222734.888084,18799444414.599796
1,148,AF-AT,AF,2460.0,2420.0,645.0,634.0,1796.0,1767.0,19.0,...,13239.0,15255.0,AFG,AUT,20497128600.336327,19134221744.529369,18116572399.129799,18753456506.570824,18053222734.888084,18799444414.599796
2,149,AF-AU,AF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20963.0,23587.0,AFG,AUS,20497128600.336327,19134221744.529369,18116572399.129799,18753456506.570824,18053222734.888084,18799444414.599796
3,150,AF-AW,AF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,AFG,ABW,20497128600.336327,19134221744.529369,18116572399.129799,18753456506.570824,18053222734.888084,18799444414.599796
4,151,AF-AX,AF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,AFG,ALA,20497128600.336327,19134221744.529369,18116572399.129799,18753456506.570824,18053222734.888084,18799444414.599796
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2499,28782,AO-ZM,AO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13831.0,15341.0,AGO,ZMB,135966802156.542297,90496420626.17897,52761617225.925285,73690155046.555038,79450688232.001144,70897962712.621307
2500,28785,BI-ZM,BI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2337.0,3284.0,BDI,ZMB,2705783329.804834,3104003546.264973,2644487776.500767,2723586962.840337,2667182199.51333,2576518879.823531
2501,28791,CD-ZM,CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13066.0,24161.0,COD,ZMB,35909040925.937469,37917706497.179283,37134801555.332191,38019264794.82634,47568210009.817162,51775829877.208817
2502,28801,MZ-ZM,MZ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,561.0,761.0,MOZ,ZMB,17978246586.066242,16208985769.614956,12069051237.171114,13264640645.776791,15017358750.611343,15512759174.573046
2503,28817,MZ-ZW,MZ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,51767.0,53086.0,MOZ,ZWE,17978246586.066242,16208985769.614956,12069051237.171114,13264640645.776791,15017358750.611343,15512759174.573046

Merging Destination GDP into GDP_merged Data

In [8]:
GDP_merged = GDP_merged.merge(destination_gpd_frame,on = 'destination_alpha_3', how = 'left')
GDP_merged

,Unnamed: 0,from_to,origin_country,ESTAT_2014_T_T_cit,ESTAT_2014_T_T_res,ESTAT_2014_T_<15_cit,ESTAT_2014_T_<15_res,ESTAT_2014_T_15-64_cit,ESTAT_2014_T_15-64_res,ESTAT_2014_T_>64_cit,...,origin_gdp_2016,origin_gdp_2017,origin_gdp_2018,origin_gdp_2019,destination_gdp_2014,destination_gdp_2015,destination_gdp_2016,destination_gdp_2017,destination_gdp_2018,destination_gdp_2019
0,147,AF-AR,AF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,18116572399.129799,18753456506.570824,18053222734.888084,18799444414.599796,526319673731.638306,594749285413.212402,557532320662.95459,643628393281.364014,524819892360.175781,447754683615.224548
1,148,AF-AT,AF,2460.0,2420.0,645.0,634.0,1796.0,1767.0,19.0,...,18116572399.129799,18753456506.570824,18053222734.888084,18799444414.599796,442584815286.033752,381971148530.542786,395837353031.499023,417261151844.977173,454991174096.101624,444596155845.254211
2,149,AF-AU,AF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,18116572399.129799,18753456506.570824,18053222734.888084,18799444414.599796,1468597690006.215088,1351768945139.113525,1207580901578.723633,1326882104817.002686,1429733668185.905273,1394671325960.568115
3,150,AF-AW,AF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,18116572399.129799,18753456506.570824,18053222734.888084,18799444414.599796,2790849720.670391,2962907262.569832,2983635195.530726,3092429050.27933,3276184357.541899,3395798882.681564
4,151,AF-AX,AF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,18116572399.129799,18753456506.570824,18053222734.888084,18799444414.599796,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2499,28782,AO-ZM,AO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,52761617225.925285,73690155046.555038,79450688232.001144,70897962712.621307,27141023558.082859,21251216798.776245,20958412538.309345,25873601260.835304,26311507273.673538,23308667781.225754
2500,28785,BI-ZM,BI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2644487776.500767,2723586962.840337,2667182199.51333,2576518879.823531,27141023558.082859,21251216798.776245,20958412538.309345,25873601260.835304,26311507273.673538,23308667781.225754
2501,28791,CD-ZM,CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,37134801555.332191,38019264794.82634,47568210009.817162,51775829877.208817,27141023558.082859,21251216798.776245,20958412538.309345,25873601260.835304,26311507273.673538,23308667781.225754
2502,28801,MZ-ZM,MZ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12069051237.171114,13264640645.776791,15017358750.611343,15512759174.573046,27141023558.082859,21251216798.776245,20958412538.309345,25873601260.835304,26311507273.673538,23308667781.225754
2503,28817,MZ-ZW,MZ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12069051237.171114,13264640645.776791,15017358750.611343,15512759174.573046,19495519600,19963120600,20548678100,17584890936.652306,34156069918.06094,21832234921.176224

Removing '..' values from the data type

In [9]:
GDP_merged.replace(to_replace = '..', value = '', inplace = True)

Changes the Datatype of the merged columns and dropping ''Unnamed: 0' column

In [10]:
GDP_merged.drop(['Unnamed: 0'],axis=1, inplace=True)
GDP_merged[['destination_gdp_2014', 'destination_gdp_2015','destination_gdp_2016','destination_gdp_2017','destination_gdp_2018','destination_gdp_2019', 'origin_gdp_2014', 'origin_gdp_2015', 'origin_gdp_2016','origin_gdp_2017','origin_gdp_2018','origin_gdp_2019']] = GDP_merged[['destination_gdp_2014', 'destination_gdp_2015','destination_gdp_2016','destination_gdp_2017','destination_gdp_2018','destination_gdp_2019', 'origin_gdp_2014', 'origin_gdp_2015', 'origin_gdp_2016','origin_gdp_2017','origin_gdp_2018','origin_gdp_2019']].apply(pd.to_numeric)

Creating new data set file in a "New" folder

In [11]:
GDP_merged.to_csv("New/merged_Dataset.csv", index=False)